 Network network  Creating
 Network network  Created
 Container krymancer-db-1  Creating
 Container krymancer-db-1  Created
 Container krymancer-api2-1  Creating
 Container krymancer-api1-1  Creating
 Container krymancer-api2-1  Created
 Container krymancer-api1-1  Created
 Container krymancer-nginx-1  Creating
 Container krymancer-nginx-1  Created
Attaching to api1-1, api2-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api2-1   | Unhandled Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'PORT is null')
api2-1   |    at Program.<<Main>$>d__0.MoveNext() + 0x1a9
api2-1   | --- End of stack trace from previous location ---
api2-1   |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
api2-1   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
api2-1   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
api2-1   |    at Program.<Main>(String[] args) + 0x24
api2-1   |    at rinha!<BaseAddress>+0x9fddec
api1-1   | Unhandled Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'PORT is null')
api1-1   |    at Program.<<Main>$>d__0.MoveNext() + 0x1a9
api1-1   | --- End of stack trace from previous location ---
api1-1   |    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
api1-1   |    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
api1-1   |    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
api1-1   |    at Program.<Main>(String[] args) + 0x24
api1-1   |    at rinha!<BaseAddress>+0x9fddec
db-1     | performing post-bootstrap initialization ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
api2-1 exited with code 139
api1-1 exited with code 139
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-19 09:45:46.103 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-19 09:45:46.107 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-19 09:45:46.115 UTC [51] LOG:  database system was shut down at 2024-02-19 09:45:43 UTC
db-1     | 2024-02-19 09:45:46.121 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | INSERT 0 5
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/postgresql.conf
db-1     | 
db-1     | waiting for server to shut down...2024-02-19 09:45:46.332 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-19 09:45:46.336 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-19 09:45:46.337 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-19 09:45:46.338 UTC [49] LOG:  shutting down
db-1     | 2024-02-19 09:45:46.340 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-19 09:45:46.822 UTC [49] LOG:  checkpoint complete: wrote 931 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.275 s, sync=0.185 s, total=0.485 s; sync files=305, longest=0.160 s, average=0.001 s; distance=4278 kB, estimate=4278 kB; lsn=0/19185D8, redo lsn=0/19185D8
db-1     | 2024-02-19 09:45:46.827 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-19 09:45:46.857 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-19 09:45:46.857 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-19 09:45:46.857 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-19 09:45:46.863 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-19 09:45:46.871 UTC [66] LOG:  database system was shut down at 2024-02-19 09:45:46 UTC
db-1     | 2024-02-19 09:45:46.878 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/19 09:45:49 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:45:52 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:45:55 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:45:57 [error] 21#21: *5 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:45:59 [error] 21#21: *6 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:05 [error] 21#21: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:08 [error] 21#21: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:11 [error] 21#21: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:13 [error] 21#21: *11 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:15 [error] 21#21: *12 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:20 [error] 21#21: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:23 [error] 21#21: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:26 [error] 21#21: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:28 [error] 21#21: *17 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:30 [error] 21#21: *18 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:35 [error] 21#21: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:38 [error] 21#21: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:41 [error] 21#21: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:43 [error] 21#21: *23 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:45 [error] 21#21: *24 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:50 [error] 21#21: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:53 [error] 21#21: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:56 [error] 21#21: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:46:58 [error] 21#21: *29 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:00 [error] 21#21: *30 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:05 [error] 21#21: *31 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:09 [error] 21#21: *31 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:12 [error] 21#21: *31 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:14 [error] 21#21: *35 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:19 [error] 21#21: *36 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.4:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:19 [error] 21#21: *36 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:24 [error] 21#21: *38 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:27 [error] 21#21: *38 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.96.3:80/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:27 [error] 21#21: *38 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/19 09:47:29 [error] 21#21: *41 no live upstreams while connecting to upstream, client: 192.168.96.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-19 09:47:32.164 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-19 09:47:32.167 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-19 09:47:32.169 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-19 09:47:32.170 UTC [64] LOG:  shutting down
db-1     | 2024-02-19 09:47:32.173 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-19 09:47:32.234 UTC [64] LOG:  checkpoint complete: wrote 47 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.036 s, total=0.064 s; sync files=14, longest=0.031 s, average=0.003 s; distance=260 kB, estimate=260 kB; lsn=0/19599C0, redo lsn=0/19599C0
db-1     | 2024-02-19 09:47:32.238 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
